[package]
name = "piecewise-rt"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]

[dependencies]
nix = "0.8.0"
intrusive-collections = "0.6"

[dev-dependencies]
quickcheck = "0.3"
