[package]
name = "proff"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]

build = "build.rs"

[dependencies]
lalrpop-util = "0.12.4"
rustyline = "1.0.0"

[build-dependencies.lalrpop]
version = "0.12.4"
