[package]
name = "interpreter"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]

[dependencies]
pcws-gc = { path = "../gc"}
pcws-domain = { path = "../domain"}
combine = "3.0.0-beta.1"
