[package]
name = "interpreter"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]

build = "build.rs"

[dependencies]
pcws-gc = { path = "../gc"}
pcws-domain = { path = "../domain"}

[build-dependencies]
peg = "0.5"
