[package]
name = "interpreter"
version = "0.1.0"
authors = ["Pauli Jaakkola <pauli.jaakkola@iki.fi>"]

build = "build.rs"

[dependencies]
gc = "*"
gc_derive = "*"
nix = "0.9"
intrusive-collections = "0.7"

[build-dependencies]
peg = "0.5"
